exclude:
  - .DS_Store
  - .gitignore
  - .vscode/
  - Dispatch/
  - IFCMALL/
  - bootstrap/
  - climateproject/
  - cafe24/assets/video/
  - hongkongsight/
  - img/profile.png
  - img/profile13.png
  - img/uiux_mockup.png
  - introduce/CHOIINYOUNG_CV2.pdf
  - uiux/
